        
#--------------Browsers---------------------#
fireFox=Yes
IE=Yes
chrome=yes
safari=no
maximizeBrowser=Yes

#!-- breakPoint - This refers to the 3 breakpoints DESKTOP, TABLET, or MOBILE --!
#!-- operatingSystem - This refers to the OS either IOS, ANDROID, or Windows. --!
#------------------------------------------#
breakPoint=Desktop
operatingSystem=Mac

#Wait Time
#------------------------------------------#
elementWaitInSeconds=20

#Application URl
#------------------------------------------#
lazadaURL= https://www.lazada.co.id/#?
shopeeURL= https://shopee.co.id/
zxingURL = https://zxing.appspot.com/generator
qrDecoderURL = https://m28dev.github.io/qrdecoder/